// src/Data/TopData.jsx
export const topThingsData = {
  tajmahal: {
    destinationTitle: "Taj Mahal",
    destinationLocation: "Agra, Uttar Pradesh",
    heroImage: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1600",
    intro: "From the ethereal glow of sunrise over white marble to hidden Mughal lanes, these eight experiences reveal the many faces of Agra's crown jewel.",
    experiences: [
      {
        id: 1,
        title: "Sunrise at Taj Mahal",
        subtitle: "Watch the marble wake up",
        image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1200",
        where: "East Gate, Taj Mahal Complex, Agra",
        description: "Few sights in the world match the Taj Mahal at first light. As the sun crests the horizon, the white marble shifts from pale silver to a warm blush pink, then settles into dazzling ivory. Arrive at the East Gate at least 30 minutes before opening to be among the first through the turnstiles — the reflecting pool will be perfectly still, doubling the monument in a mirror of liquid gold.",
        tips: "Gates open at sunrise. Buy tickets online the day before to skip the queue. Bring a light jacket — mornings can be cool October–February.",
        duration: "2–3 hours",
        bestTime: "Sunrise, year-round",
      },
      {
        id: 2,
        title: "Agra Fort Tour",
        subtitle: "Inside the Red Palace of Mughal power",
        image: "https://media.istockphoto.com/id/1169495248/photo/agra-fort-medieval-indian-fort-at-agra-india-at-sunrise.jpg?s=612x612&w=0&k=20&c=EI9BXzCutx2gRuPCFUDSirZg9Hfc7G_kGfFbmVBmSEc=",
        where: "Rakabganj, Agra Fort, Agra",
        description: "Just 2.5 km from the Taj, Agra Fort is a UNESCO World Heritage site that served as the main residence of the Mughal Emperors until 1638. The massive red sandstone walls enclose palaces, audience halls, mosques, and gardens spanning 380,000 sq m.",
        tips: "Combine with Taj Mahal on the same day. Hire a certified Archaeological Survey of India guide at the gate for context that transforms the ruins into stories.",
        duration: "2–3 hours",
        bestTime: "Morning, October–March",
      },
      {
        id: 3,
        title: "Sunset at Mehtab Bagh",
        subtitle: "The mirror view across the Yamuna",
        image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1200",
        where: "Mehtab Bagh, Dharam Pura, Agra",
        description: "Mehtab Bagh — the 'Moonlight Garden' — sits directly across the Yamuna River from the Taj Mahal and was originally designed as the final garden of a series commissioned by Emperor Babur. Today it is the most serene sunset spot in Agra: fewer crowds, a wide lawn, and an unobstructed view of the Taj glowing in the amber light of dusk.",
        tips: "Entry fee is separate from the Taj. Visit 1 hour before sunset. Photography is stunning from the river banks just below the garden walls.",
        duration: "1.5 hours",
        bestTime: "Late afternoon, October–February",
      },
      {
        id: 4,
        title: "Itmad-ud-Daula",
        subtitle: "The Baby Taj — first marble mausoleum of the Mughals",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/c9/I%27tim%C4%81d-ud-Daulah%2C_Agra.jpg",
        where: "Moti Bagh, Agra",
        description: "Built by Empress Nur Jahan for her father Mirza Ghiyas Beg between 1622 and 1628, Itmad-ud-Daula is often called the 'Baby Taj' but predates the Taj Mahal by nearly two decades. It was the first Mughal structure built entirely of white marble and the first to use the pietra dura technique — inlaying semi-precious stones into marble — that would later define the Taj Mahal.",
        tips: "Visit early morning for soft light. The interior stonework is extraordinarily detailed — bring a torch to appreciate the inlay work on the ceiling panels.",
        duration: "1.5 hours",
        bestTime: "Morning",
      },
      {
        id: 5,
        title: "Fatehpur Sikri Trip",
        subtitle: "The ghost city of Emperor Akbar",
        image: "https://t3.ftcdn.net/jpg/02/02/60/78/360_F_202607822_56X4UHztDCbXM1pUSdniwjKJIX51gkfb.jpg",
        where: "Fatehpur Sikri, 40 km from Agra",
        description: "Akbar built this entire walled city as his new capital in 1571, only to abandon it 14 years later — possibly due to water scarcity. The result is one of the best-preserved Mughal cities in existence, a haunting complex of palaces, courts, and a magnificent mosque frozen in the 16th century.",
        tips: "Hire a shared cab from Agra (about 1 hour). Combine with a stop at the Agra Bear Rescue Facility on the way back. Beware of persistent unofficial guides.",
        duration: "Half day",
        bestTime: "Morning, October–March",
      },
      {
        id: 6,
        title: "Kinari Bazar Walk",
        subtitle: "Lose yourself in Agra's oldest market lanes",
        image: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?w=1200",
        where: "Kinari Bazar, Sadar Bazar, Agra",
        description: "Step away from the monuments and into the sensory chaos of Kinari Bazar — Agra's centuries-old wholesale market for zari (gold thread) embroidery, bridal wear, and traditional dupattas. The lanes are barely wide enough for two people to pass; rickshaws squeeze through honking; rooftop workers lower fabric bolts on ropes. This is where Agra's artisans have traded for generations.",
        tips: "Best visited in the evening when traders are active. Bargain firmly — initial prices are often 3× the fair price. Try the bedai-jalebi breakfast from roadside vendors in the morning.",
        duration: "1–2 hours",
        bestTime: "Evening",
      },
      {
        id: 7,
        title: "Savor Agra Petha",
        subtitle: "The sweet that built a city's identity",
        image: "https://travelxamp.com/wp-content/uploads/2021/02/Petha-1024x1024.jpeg",
        where: "Panchhi Petha, Sadar Road, Agra",
        description: "Petha — a translucent candy made from ash gourd, sugar, and various flavorings — is Agra's most famous export and has been made here for over 400 years. Legend holds that Mughal emperor Shah Jahan ordered his royal cooks to create a sweet as white and pure as the Taj Mahal.",
        tips: "Buy vacuum-packed boxes for travel — they last up to 30 days without refrigeration. Angoori Petha (small grape-shaped pieces in syrup) is the most traditional variety.",
        duration: "30 minutes",
        bestTime: "Any time",
      },
      {
        id: 8,
        title: "Mughal Heritage Walk",
        subtitle: "Hidden village, hidden views",
        image: "https://thetajwondertours.com/wp-content/uploads/2022/07/sa3.jpg",
        where: "Kachhpura Village, across the Yamuna from Taj Mahal",
        description: "Cross the Yamuna by boat and walk through Kachhpura — a small village that sits on the opposite bank of the river, directly behind the Taj Mahal. Few tourists make it here, which means you walk through quiet mustard fields, past mud-brick homes, and along the riverbank with an extraordinary unobstructed view of the Taj's rear garden, the moongate, and the four minarets.",
        tips: "Book through a certified heritage walk operator. Best done in the morning golden hour. The boat crossing takes about 10 minutes each way.",
        duration: "2–3 hours",
        bestTime: "Early morning",
      },
    ],
  },
  jaipur: {
    destinationTitle: "Jaipur",
    destinationLocation: "Rajasthan",
    heroImage: "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?w=1600",
    intro: "The Pink City dazzles with royal forts, star-gazing observatories, bazaars glittering with gemstones, and evenings lit by folk fire dancers. Here are eight ways to live it.",
    experiences: [
      {
        id: 1,
        title: "Amer Fort Ride",
        subtitle: "Ascend by jeep to Rajputana grandeur",
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/16/fe/87/amer-elephant-safari.jpg?w=1200&h=1200&s=1",
        where: "Amer, 11 km from Jaipur city centre",
        description: "Perched on a ridge above Maota Lake, Amer Fort is the definitive image of Rajput military architecture. Built in 1592 by Raja Man Singh I, the fort is a labyrinth of palaces, gardens, temples, and halls built over two centuries. The Sheesh Mahal (Palace of Mirrors) is perhaps India's most breathtaking interior — thousands of mirror fragments inlaid into plasterwork reflect a single candle into a galaxy of stars.",
        tips: "Book jeep rides at the bottom of the hill — shared jeeps are cheaper. Arrive before 9 AM to beat the tourist groups. The sound-and-light show in the evening is worth attending.",
        duration: "3–4 hours",
        bestTime: "Morning, October–March",
      },
      {
        id: 2,
        title: "Hawa Mahal",
        subtitle: "953 windows and the world's most photographed facade",
        image: "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?w=1200",
        where: "Badi Choupad, J.D.A. Market, Pink City, Jaipur",
        description: "The Hawa Mahal — Palace of Winds — was built in 1799 by Maharaja Sawai Pratap Singh to allow royal women, who observed strict purdah, to watch street festivals below without being seen. Its honeycombed facade with 953 latticed windows (jharokhas) creates a natural air-conditioning effect that keeps the interior cool.",
        tips: "Photograph the facade from the rooftop cafe across the road (Wind View Cafe) for the classic shot. Entry fee is minimal. Visit the interior — most tourists only photograph the exterior.",
        duration: "1 hour",
        bestTime: "Early morning for facade photography",
      },
      {
        id: 3,
        title: "City Palace",
        subtitle: "A living royal palace in the heart of Jaipur",
        image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=1200",
        where: "Tulsi Marg, Gangori Bazaar, Pink City, Jaipur",
        description: "Unlike many Indian palaces turned into museums, City Palace is still home to the royal family of Jaipur, who occupy the Chandra Mahal section. The public areas include the Mubarak Mahal (a museum of royal textiles and costumes), the armory, and the Diwan-i-Khas containing two giant sterling silver vessels weighing 340 kg each — used to transport Gangajal (sacred Ganges water) to England for Maharaja Sawai Madho Singh II's 1902 coronation visit.",
        tips: "Opt for the premium ticket that includes a royal tea ceremony. The museum's textile galleries are extraordinary. Avoid Mondays when some sections close.",
        duration: "2–3 hours",
        bestTime: "Morning",
      },
      {
        id: 4,
        title: "Jantar Mantar",
        subtitle: "The world's largest stone observatory",
        image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=1200",
        where: "Gangori Bazaar, Badi Chaupar, Pink City, Jaipur",
        description: "Built by Maharaja Jai Singh II between 1727 and 1734, Jantar Mantar is a collection of 19 astronomical instruments constructed from stone and marble — still functional and accurate to within two seconds today. The Samrat Yantra sundial stands 27 metres tall and can measure time to an accuracy of half a second.",
        tips: "Hire the official guide at the entrance (prices fixed by ASI). Visit on a sunny day when the sundials work. Immediately adjacent to City Palace — combine both in one morning.",
        duration: "1–1.5 hours",
        bestTime: "Morning (for functioning sundials)",
      },
      {
        id: 5,
        title: "Nahargarh Fort Sunset",
        subtitle: "Jaipur's skyline from 700 feet above",
        image: "https://t3.ftcdn.net/jpg/08/03/14/06/360_F_803140668_a8hZXCNWkAIeEqO7kGSrgo4yt36BAncN.jpg",
        where: "Krishna Nagar, Brahampuri, Jaipur",
        description: "Nahargarh ('Abode of Tigers') Fort crowns the Aravalli Hills overlooking Jaipur and was built by Maharaja Jai Singh II in 1734 as a retreat and a defensive ring around the city. Today it is famous for the panoramic sunset view across the entire Pink City — a grid of terracotta and pink buildings glowing in the evening light, with Jal Mahal floating in the lake below.",
        tips: "Go by auto-rickshaw or cab — the road is steep. Arrive 45 minutes before sunset to secure a good spot on the ramparts. The restaurant inside the fort serves good Rajasthani thali.",
        duration: "2 hours",
        bestTime: "Late afternoon",
      },
      {
        id: 6,
        title: "Chokhi Dhani Dinner",
        subtitle: "An entire Rajasthani village, recreated",
        image: "https://images.unsplash.com/photo-1561501900-3701fa6a0864?w=1200",
        where: "Chokhi Dhani, Tonk Road, 20 km from Jaipur",
        description: "Chokhi Dhani is an ethno-resort and village complex that authentically recreates a traditional Rajasthani village experience. Entry includes an unlimited traditional Rajasthani thali dinner served on banana leaves by turbaned waiters who keep refilling until you beg them to stop — dal baati churma, ker sangri, gatte ki sabzi, multiple chutneys, and mishri mawa mithai.",
        tips: "Book tickets online to avoid evening queues. Vegetarian only. Wear comfortable clothes — the experience involves sitting on the ground for dinner.",
        duration: "3–4 hours (evening)",
        bestTime: "Evening, year-round",
      },
      {
        id: 7,
        title: "Jaigarh Fort",
        subtitle: "Home to the world's largest cannon on wheels",
        image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=1200",
        where: "Devisinghpura, Amer, Jaipur",
        description: "Jaigarh Fort — built in 1726 to guard Amer Fort from above — contains the Jaivana cannon, cast in 1720, the largest cannon on wheels ever made. It weighs 50 tonnes, has a barrel 6.15 m long, and when it was test-fired (just once, in the 18th century), the ball landed 35 km away.",
        tips: "The same entry ticket covers both Jaigarh and Amer Fort. Jaigarh is far less crowded. A combined rickshaw tour of Amer–Jaigarh–Nahargarh is the best way to see all three.",
        duration: "1.5 hours",
        bestTime: "Morning",
      },
      {
        id: 8,
        title: "Johari Bazar Shopping",
        subtitle: "Precious stones, block prints, and Rajasthani quilts",
        image: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?w=1200",
        where: "Johari Bazaar Road, Pink City, Jaipur",
        description: "Jaipur is the world's gemstone cutting and trading capital — nearly 80% of the world's precious and semi-precious stone cutting happens here. Johari Bazar (Jeweler's Market) is the epicentre, a kilometre-long street of shops selling Kundan, Meenakari, and Polki jewelry, block-printed fabrics, Jaipuri quilts (razai), and blue pottery.",
        tips: "Always bargain — starting prices are inflated. For reliable gems, visit GIA-certified dealers only. The best block-print fabrics are at Anokhi and Cottons stores for quality control.",
        duration: "2–3 hours",
        bestTime: "Morning",
      },
    ],
  },
  goa: {
    destinationTitle: "Goa",
    destinationLocation: "Goa",
    heroImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1600",
    intro: "Sun-bleached churches, spice-scented markets, emerald rice paddies, and some of India's finest beaches — Goa rewards those who go beyond the shoreline.",
    experiences: [
      {
        id: 1,
        title: "Baga Beach Sunrise",
        subtitle: "Golden light on the Arabian Sea",
        image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200",
        where: "Baga Beach, North Goa",
        description: "Baga at sunrise is a different creature from the sun-lounger scene of midday. The beach is empty except for fishermen dragging colourful wooden trawlers (ramponkar boats) onto the sand and sorting overnight catches of kingfish, mackerel, and prawns. The light is extraordinary — low, golden, painting long shadows across wet sand.",
        tips: "Stay nearby to make a 6 AM start effortless. The fish market at the northern end of the beach is one of Goa's best photo subjects in the morning.",
        duration: "2 hours",
        bestTime: "November–February",
      },
      {
        id: 2,
        title: "Old Goa Churches",
        subtitle: "The Vatican of the East",
        image: "https://media.istockphoto.com/id/1481931865/photo/interior-of-catholic-church-of-st-francis-of-assisi-in-goa-velha-goa-india-asia.jpg?s=612x612&w=0&k=20&c=Fgu6jBlAj4PKR7hCWDOgC7EkKsKipH7m7VzUTQgZUE0=",
        where: "Old Goa, 10 km from Panaji",
        description: "Old Goa was once the capital of Portugal's eastern empire and today its 16th-century churches are among the finest examples of Baroque architecture in Asia. The Basilica of Bom Jesus houses the relics of St. Francis Xavier, exposed once every ten years for veneration. Together these churches form a UNESCO World Heritage site.",
        tips: "Visit on a weekday morning to avoid weekend crowds. The archaeological museum near the ruins of St. Augustine's Tower provides context for the Portuguese era.",
        duration: "2–3 hours",
        bestTime: "Morning",
      },
      {
        id: 3,
        title: "Dudhsagar Falls Trek",
        subtitle: "Four tiers of white thunder through jungle",
        image: "https://images.unsplash.com/photo-1518002054494-3a6f94352e9d?w=1200",
        where: "Dudhsagar, Goa-Karnataka border",
        description: "Dudhsagar ('Sea of Milk') is one of India's tallest waterfalls at 310 metres, cascading in four dramatic tiers through the dense Western Ghats forest. The falls are most spectacular between July and October during the monsoon, but the trek is usually only possible October–May. The journey itself is half the adventure — a jeep ride through jungle tracks, a river crossing, and then a swim in the natural pool at the base.",
        tips: "Book an organized jeep safari from Collem or Mollem — it's impossible to reach independently during closure periods. Wear clothes you can get wet in.",
        duration: "Full day",
        bestTime: "October–May",
      },
      {
        id: 4,
        title: "Spice Plantation Tour",
        subtitle: "Walk through cardamom, vanilla, and pepper in the wild",
        image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=1200",
        where: "Ponda, Central Goa",
        description: "Goa's hinterland is threaded with working spice plantations that have been producing cardamom, pepper, vanilla, nutmeg, cinnamon, and turmeric since the Portuguese era. A guided tour walks you through the growing conditions of each spice — you can taste fresh peppercorns off the vine, smell crushed cardamom pods, and see vanilla orchids in flower. The tour ends with a traditional Goan lunch served on banana leaves.",
        tips: "Book in advance for the included lunch. The Ponda area also has some of Goa's finest Hindu temples, including Shri Mangesh Temple — worth combining into a half-day.",
        duration: "Half day",
        bestTime: "October–April",
      },
      {
        id: 5,
        title: "Anjuna Flea Market",
        subtitle: "40 years of hippie-to-hipster trading",
        image: "https://images.unsplash.com/photo-1555529902-5261145633bf?w=1200",
        where: "Anjuna Beach, North Goa",
        description: "The Anjuna Flea Market began in the 1970s when Western hippies who had overstayed their budgets sold their belongings to fund the next month's stay. Today it runs every Wednesday from November to April and has evolved into an extraordinary bazaar — Tibetan traders selling silver jewelry beside Rajasthani block-print vendors, Kashmiri shawl sellers, Indonesian batik cloth merchants, and stalls of vintage cameras, old vinyl records, and handmade leather goods.",
        tips: "Go at opening (8–9 AM) for the best selection before the heat builds. Bargaining is expected. Keep small change handy — vendors rarely have change for 500-rupee notes.",
        duration: "2–3 hours",
        bestTime: "Wednesday mornings, November–April",
      },
      {
        id: 6,
        title: "Chapora Fort Sunset",
        subtitle: "The Dil Chahta Hai fort — iconic views at dusk",
        image: "https://images.unsplash.com/photo-1586500036706-41963de24d8b?w=1200",
        where: "Chapora, Bardez, North Goa",
        description: "Chapora Fort became famous internationally after appearing in the Bollywood film Dil Chahta Hai, but long before Bollywood it was a Portuguese fortification built over a much older Adil Shah structure. Today its crumbling laterite walls enclose nothing but wind and grass — but the view from the ramparts of the Chapora River meeting the Arabian Sea, with Vagator Beach and Anjuna curving in the distance, is spectacular at sunset.",
        tips: "Drive a scooter up — the last stretch is steep and the road is rough. No facilities at the fort, so bring water. Combine with sundowners at a Vagator beach cafe afterwards.",
        duration: "1.5 hours",
        bestTime: "Late afternoon",
      },
      {
        id: 7,
        title: "Kayaking in Backwaters",
        subtitle: "Mangrove silence on the Cumbarjua Canal",
        image: "https://media.istockphoto.com/id/1031430208/photo/exploring-the-backwaters-of-monroe-island.jpg?s=612x612&w=0&k=20&c=mwKRt35O5N4hX9GS8Q3gthwU14-J11iR4HPpn4xdmuQ=",
        where: "Cumbarjua Canal, Central Goa",
        description: "Goa's interior network of tidal creeks and mangrove-lined canals is one of the state's most underrated environments. The Cumbarjua Canal connects the Mandovi and Zuari rivers and is home to mugger crocodiles, kingfishers, egrets, and freshwater dolphins. Guided kayaking tours paddle silently through the mangrove tunnels at dawn — a completely different Goa from the beach experience, more Kerala backwaters than coastal party town.",
        tips: "Book with an eco-operator who provides life jackets and briefing. Dawn departures are best for wildlife. Wear sunscreen and long sleeves — shade is minimal on open water.",
        duration: "3 hours",
        bestTime: "November–March, dawn departures",
      },
      {
        id: 8,
        title: "Goan Seafood Trail",
        subtitle: "Eat where the fishermen eat",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200",
        where: "Cavelossim, Benaulim, and Colva, South Goa",
        description: "The finest Goan food is not in the tourist belt restaurants but in the small local eateries (xacks) and family homes of South Goa's fishing villages. A prawn balchão (fiery pickled prawns), a fish recheado (pomfret stuffed with spiced masala and grilled), and a crab xacuti served with sannas (steamed rice cakes) makes a lunch to remember. Martin's Corner restaurant in Betalbatim started as a simple shack and has served the same family recipes for 40 years.",
        tips: "Avoid restaurants on beach tourist corridors — quality drops and prices rise. Ask any local where they themselves eat. Kingfish and pomfret are Goa's finest species.",
        duration: "Lunch or dinner",
        bestTime: "Year-round (best catch November–March)",
      },
    ],
  },
  kerala: {
    destinationTitle: "Kerala",
    destinationLocation: "God's Own Country",
    heroImage: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1600",
    intro: "Floating through mirror-still backwaters, climbing misty tea estates, watching Kathakali masks transform in the lamplight — Kerala's experiences stay with you long after you leave.",
    experiences: [
      {
        id: 1,
        title: "Houseboat in Alleppey",
        subtitle: "Drift through the Venice of the East",
        image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200",
        where: "Alleppey (Alappuzha) Backwaters",
        description: "A kettuvallam — a traditional rice barge converted into a floating home — is the quintessential Kerala experience. These handcrafted boats with bamboo-mat roofs drift through 900 km of interconnected canals, rivers, lakes, and inlets that make up the Kerala backwaters. An overnight houseboat experience includes a resident cook who prepares fresh Kerala meals: karimeen (pearl spot fish) pollichathu, prawn moilee, and appam with stew, eaten as the sun sets over Vembanad Lake.",
        tips: "Book a certified 'Green Palm' houseboat for eco-standards. Avoid peak Christmas/New Year when prices triple and canals are congested. A two-night minimum reveals the quieter inner canals.",
        duration: "Overnight or 2 nights",
        bestTime: "September–March",
      },
      {
        id: 2,
        title: "Munnar Tea Trails",
        subtitle: "Walk through 50,000 acres of rolling green",
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200",
        where: "Munnar, Idukki District",
        description: "Munnar sits at 1,600 metres in the Western Ghats and is carpeted with tea plantations established by British planters in the 1870s. The Kolukkumalai Tea Estate — the world's highest tea estate at 2,150 metres — can only be reached by jeep on a dirt track and still processes tea in 100-year-old wooden machinery. Walking the plucking rows at dawn, when mist rolls through the valley and pluckers in bright saris work their way along, is one of India's most cinematically beautiful experiences.",
        tips: "Kolukkumalai requires a dedicated half-day jeep excursion — book the day before in Munnar. The Tata Tea Museum in Munnar town provides the plantation history context.",
        duration: "Half to full day",
        bestTime: "October–March",
      },
      {
        id: 3,
        title: "Kathakali Dance Performance",
        subtitle: "Two hours of myth in paint and gesture",
        image: "https://images.unsplash.com/photo-1545063914-a1a6ec821c88?w=1200",
        where: "Kerala Kalamandalam, Thrissur / various venues in Kochi and Thiruvananthapuram",
        description: "Kathakali is a 500-year-old classical dance drama of Kerala rooted in Hindu mythology, performed in elaborate costumes weighing up to 35 kg and makeup that takes 4–6 hours to apply. Performers communicate entire epics from the Mahabharata and Ramayana through a codified language of 24 primary hand gestures (mudras) and 9 facial expressions.",
        tips: "The best performances are at Kerala Kalamandalam (a UNESCO heritage institution). Shorter 45-minute tourist shows at Cultural Centres in Fort Kochi are good introductions. Sit close enough to see the face expressions.",
        duration: "2–4 hours including makeup viewing",
        bestTime: "Year-round (monsoon season performances are especially atmospheric)",
      },
      {
        id: 4,
        title: "Periyar Tiger Reserve",
        subtitle: "Elephants on the lake shore at dawn",
        image: "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=1200",
        where: "Thekkady, Idukki District",
        description: "Periyar is the most visited wildlife reserve in South India and one of Project Tiger's original reserves. The early morning boat safari on Periyar Lake offers the highest wildlife density per hour of any Indian national park experience — herds of wild elephants come to the shore at dawn to drink, gaur (Indian bison) graze the meadows, and otters fish in the shallows.",
        tips: "Book the KTDC early morning boat safari online 2 days in advance. The night patrol walk run by ex-poachers-turned-guides is a remarkable conservation success story worth supporting.",
        duration: "Half to full day",
        bestTime: "October–April",
      },
      {
        id: 5,
        title: "Ayurveda Treatment",
        subtitle: "Three thousand years of healing in one hour",
        image: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=1200",
        where: "Various centres across Kerala",
        description: "Kerala is the home of authentic Ayurveda — not the spa-lite version found elsewhere in India, but classical therapeutic treatments prescribed by doctors following the Ashtanga Hridayam text written 1,500 years ago. A proper Ayurvedic consultation begins with pulse diagnosis by a vaidya (physician), then prescribes treatments ranging from a simple Abhyanga (full-body warm oil massage) to the intensive Panchakarma detoxification program lasting 7–21 days.",
        tips: "Avoid 'Ayurveda' offerings in tourist hotels which are rarely authentic. Seek out hospitals affiliated with Kerala Ayurveda Ltd or those certified by Kerala Tourism. A consultation should precede any treatment.",
        duration: "1 hour for a single treatment; up to 21 days for Panchakarma",
        bestTime: "June–August (monsoon) or year-round",
      },
      {
        id: 6,
        title: "Varkala Cliff Walk",
        subtitle: "Dramatic red laterite cliffs above the Arabian Sea",
        image: "https://images.unsplash.com/photo-1586500036706-41963de24d8b?w=1200",
        where: "Varkala, Thiruvananthapuram District",
        description: "Varkala's signature landscape is its crumbling red laterite cliffs that drop directly into the Arabian Sea — a geological rarity on India's coastline. The cliff-top promenade runs for nearly 2 km lined with yoga studios, ayurvedic massage centres, fresh juice bars, and restaurants with sea-view terraces. Below, Papanasam Beach is considered sacred — pilgrims immerse ashes of the deceased in its waters, believing it washes away sins.",
        tips: "Walk the cliff path at sunset for the best light and temperatures. The southern end of the cliff (Black Beach area) is quieter and less touristy.",
        duration: "1.5–2 hours",
        bestTime: "October–March",
      },
      {
        id: 7,
        title: "Kerala Cooking Class",
        subtitle: "Coconut, curry leaves, and the art of tempering",
        image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=1200",
        where: "Fort Kochi / Alleppey / Thiruvananthapuram",
        description: "Kerala cuisine is one of India's most distinct and coconut-forward culinary traditions — almost every dish includes fresh coconut milk, grated coconut, or coconut oil. A hands-on cooking class with a local family covers the making of fish curry (meen curry cooked in a clay pot with raw mango and kudampuli), prawn thoran (dry coconut stir fry), Kerala parotta layered bread, and payasam dessert.",
        tips: "Morning classes that include a spice market visit are the best format. Ask specifically for the meen curry in a clay vessel — the clay affects the flavor.",
        duration: "3–4 hours",
        bestTime: "Year-round",
      },
      {
        id: 8,
        title: "Fort Kochi Heritage Walk",
        subtitle: "Portuguese, Dutch, Jewish, and Chinese in one square kilometre",
        image: "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=1200",
        where: "Fort Kochi, Ernakulam District",
        description: "Fort Kochi is arguably Asia's most compressed layer of colonial history: the iconic Chinese fishing nets along the seafront (in use since the 14th century, brought by traders from Kublai Khan's court), the Mattancherry Palace painted by Dutch merchants, the Pardesi Synagogue in the Jewish quarter of Jew Town (one of India's oldest functioning synagogues), and St. Francis Church where Vasco da Gama was originally buried.",
        tips: "Self-guided or join a heritage walk run by Kochi Heritage Walk at 8 AM daily. The antique shops in Jew Town sell colonial-era artifacts — inspect carefully before buying.",
        duration: "2–3 hours",
        bestTime: "Morning",
      },
    ],
  },
  ladakh: {
    destinationTitle: "Ladakh",
    destinationLocation: "Union Territory of Ladakh",
    heroImage: "https://images.unsplash.com/photo-1591076482161-42ce6da69f67?w=1600",
    intro: "At the edge of the world, where mountains scrape 5,000-metre passes and monasteries hang from cliffs above turquoise rivers, Ladakh demands you slow down and breathe.",
    experiences: [
      {
        id: 1,
        title: "Pangong Lake at Dawn",
        subtitle: "The lake that changes colour six times a day",
        image: "https://images.unsplash.com/photo-1591076482161-42ce6da69f67?w=1200",
        where: "Pangong Tso, 160 km from Leh",
        description: "Pangong Tso lies at 4,350 metres on the India-China border and extends 134 km, of which only a third lies in India. Its water — fed by glaciers and snowmelt — shifts through a spectrum of blues and greens through the day as the angle of the light changes, from cold silver at dawn to deep sapphire at noon to burning copper at dusk. The shoreline is so barren and clean it looks photoshopped.",
        tips: "Requires an Inner Line Permit obtained in Leh. Drive via Chang La pass (5,360m) — acclimatise at least 2 days in Leh first. Camp at the lake's edge for the full experience.",
        duration: "Overnight trip",
        bestTime: "June–September",
      },
      {
        id: 2,
        title: "Khardung La Ride",
        subtitle: "Cross one of the world's highest motorable passes",
        image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200",
        where: "Khardung La, 39 km north of Leh",
        description: "Khardung La at 5,359 metres is one of the highest motorable passes in the world and the gateway to the Nubra Valley. The road is maintained by the Border Roads Organisation and open to civilians with permits. The summit is a lunar landscape of snow and rock with prayer flags snapping in a wind that cuts through any number of layers.",
        tips: "Acclimatise fully (minimum 3 days in Leh) before attempting. Ride early morning when the road is clearest. Tea stalls at the summit serve hot noodles.",
        duration: "Full day",
        bestTime: "June–September",
      },
      {
        id: 3,
        title: "Thiksey Monastery",
        subtitle: "Morning prayer in a 500-year-old monastery",
        image: "https://plus.unsplash.com/premium_photo-1697729578645-a9decad10b8c?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8VGhpa3NleSUyME1vbmFzdGVyeXxlbnwwfHwwfHx8MA%3D%3D",
        where: "Thiksey, 19 km from Leh",
        description: "Thiksey Gompa rises in 12 storeys from the valley floor like a white and red tiered cake and is often compared to the Potala Palace in Lhasa. Waking at 6 AM to attend the morning puja is a profound experience — 30 to 40 monks in maroon robes seat themselves in the dimly lit prayer hall, drums beat, horns sound, and the chanting begins while butter lamps flicker across ancient thankas.",
        tips: "Ask permission before entering prayer sessions and maintain silence. Photography is generally allowed but check before using flash. Stay overnight in Leh and depart by jeep at 5:30 AM.",
        duration: "2–3 hours",
        bestTime: "Early morning, year-round (closed in deep winter)",
      },
      {
        id: 4,
        title: "Nubra Valley Camel Safari",
        subtitle: "Ride a double-humped camel through Himalayan desert",
        image: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200",
        where: "Hunder Sand Dunes, Nubra Valley",
        description: "The Nubra Valley sits in the rain shadow of the Ladakh Range and contains wind-sculpted sand dunes that form an impossible landscape — high-altitude Himalayan desert at 3,100 metres. Bactrian (double-humped) camels, descended from animals used by the ancient Silk Road trading caravans, are still kept here and used for tourist rides across the dunes.",
        tips: "The camel ride is 20–30 minutes but the dune landscape is best experienced by walking among the formations. Combine with a visit to Diskit Monastery above the valley.",
        duration: "Half day in the valley",
        bestTime: "June–September",
      },
      {
        id: 5,
        title: "Tso Moriri Lake Trek",
        subtitle: "Reaching the lake the long way",
        image: "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=1200",
        where: "Tso Moriri, Changthang Plateau",
        description: "Tso Moriri is a high-altitude lake at 4,522 metres in the Changthang region, less visited than Pangong and arguably more spectacular — the mountains that surround it are higher and closer, and their reflections completely fill the lake's surface in calm conditions. The lake is a Ramsar wetland and breeding ground for bar-headed geese, black-necked cranes, and Tibetan wild ass (kiang).",
        tips: "Requires Inner Line Permit. Hire a local guide and porter from Leh — the trek crosses remote terrain with no facilities. Acclimatise thoroughly.",
        duration: "3-day trek / 1-day drive from Leh",
        bestTime: "July–September",
      },
      {
        id: 6,
        title: "Leh Palace & Old Town Walk",
        subtitle: "Nine storeys of royal history above the Indus Valley",
        image: "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=1200",
        where: "Leh Palace, Old Town, Leh",
        description: "Leh Palace was built in the 17th century by King Sengge Namgyal and predates the Potala Palace in Lhasa by 30 years — the same architectural model of a multi-storey fortress-palace built into a cliff. From its rooftop you see the entire Indus Valley spread out below, with the Himalayas to the south and Karakoram to the north.",
        tips: "Carry water and snacks for the climb. The rooftop is the goal — take your time. Namgyal Tsemo Gompa above the palace is an additional 30-minute climb with even better views.",
        duration: "2–3 hours",
        bestTime: "Morning",
      },
      {
        id: 7,
        title: "Zanskar River Rafting",
        subtitle: "White water between canyon walls",
        image: "https://plus.unsplash.com/premium_photo-1697730326303-60ca993f85dd?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8WmFuc2thciUyMFJpdmVyJTIwUmFmdGluZ3xlbnwwfHwwfHx8MA%3D%3D",
        where: "Zanskar River, Zanskar Valley",
        description: "The Zanskar River runs through a gorge so deep that in winter the frozen river surface becomes the only road between Zanskar and the outside world — the famous Chadar Trek. In summer the river is a Grade III–IV white water rafting destination. Rafting sections run from Padum to Nimmu (3–5 days) or shorter day sections near Leh.",
        tips: "Book with certified operators in Leh. Multi-day trips camp on sandy beaches at river bends. June has highest water levels; September is calmer but still excellent.",
        duration: "1 day to 5 days",
        bestTime: "June–September",
      },
      {
        id: 8,
        title: "Hemis Festival",
        subtitle: "Masked dancers in the oldest monastery courtyard",
        image: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200",
        where: "Hemis Monastery, 45 km from Leh",
        description: "Hemis Festival is Ladakh's most spectacular cultural event — a two-day Buddhist festival held annually at Hemis Monastery on the anniversary of the birth of Guru Padmasambhava (usually June or July). The monastery courtyard fills with monks in elaborate brocade costumes and painted masks performing Cham — sacred masked dances that depict the triumph of good over evil and are performed as a form of living prayer.",
        tips: "Arrive the evening before to witness the monastery preparation rituals. Book accommodation months in advance — it sells out. The outer masked dances are public; inner courtyard rituals require prior permission.",
        duration: "2 days",
        bestTime: "June–July (dates vary each year)",
      },
    ],
  },
  varanasi: {
    destinationTitle: "Varanasi",
    destinationLocation: "Uttar Pradesh",
    heroImage: "https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=1600",
    intro: "The world's oldest living city assaults every sense and then renders you still. These eight experiences reveal why Varanasi holds people for far longer than they planned.",
    experiences: [
      {
        id: 1,
        title: "Ganga Aarti at Dashashwamedh Ghat",
        subtitle: "Fire, incense, and the river at dusk",
        image: "https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=1200",
        where: "Dashashwamedh Ghat, Varanasi",
        description: "Every evening at sunset, seven priests in silk dhoti conduct a 45-minute fire ceremony at Dashashwamedh Ghat — the most sacred of Varanasi's 88 ghats. Each holds a multi-tiered oil lamp (aarti lamp) that contains 21 cotton wicks and rotates it in choreographed patterns while priests chant Sanskrit hymns. Smoke from the incense drifts over the river, flower petals float in the current, and tens of thousands of people watch from boats and the ghat steps.",
        tips: "Watch from a boat on the river for the best vantage point — book through your hotel or directly at the ghat. Arrive 30 minutes early for a good position. Photography is permitted.",
        duration: "1–1.5 hours",
        bestTime: "Daily at sunset",
      },
      {
        id: 2,
        title: "Sunrise Boat Row on the Ganges",
        subtitle: "Float past 3,000 years of unbroken ritual",
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200",
        where: "The Ghats, Varanasi",
        description: "A sunrise row along the 6-km arc of ghats from Assi to Raj Ghat is the definitive Varanasi experience. In the pre-dawn light, pilgrims descend stone steps to bathe in the Ganga; priests sit under bamboo parasols conducting private pujas; boys practice wrestling in the sand; dhobis (washermen) beat laundry against stones; and smoke rises from the ever-burning pyres of Manikarnika Ghat.",
        tips: "Negotiate a fixed rate with your boatman before departing. Sunrise (5–6 AM) is essential — midday rows miss the activity entirely. Avoid using flash photography near cremation ghats.",
        duration: "2 hours",
        bestTime: "Sunrise, year-round",
      },
      {
        id: 3,
        title: "Manikarnika Ghat Visit",
        subtitle: "The burning ghat that never sleeps",
        image: "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=1200",
        where: "Manikarnika Ghat, Varanasi",
        description: "Manikarnika is Hinduism's most sacred cremation site — a fire that Hindus believe has burned for over 3,500 years. Between 80 and 300 cremations take place here every day, every day of the year, without interruption. Arriving here confronts visitors with an acceptance of death that is entirely outside most modern experience.",
        tips: "Do not take photographs at Manikarnika — it is deeply disrespectful. Guides offering to take you to the 'burning ghat' for a donation often lead to uncomfortable situations. Visit independently and respectfully from the perimeter.",
        duration: "30 minutes",
        bestTime: "Morning or evening",
      },
      {
        id: 4,
        title: "Sarnath Day Trip",
        subtitle: "Where the Buddha gave his first sermon",
        image: "https://images.unsplash.com/photo-1524492712937-b28074a5d7da?w=1200",
        where: "Sarnath, 10 km from Varanasi",
        description: "Sarnath is one of Buddhism's four holiest sites — the deer park where Siddhartha Gautama delivered his first sermon after attaining enlightenment. The Dhamek Stupa, rising 34 metres from the ground, marks the exact spot. The archaeological museum contains the Lion Capital of Ashoka — the original sculpture that became the national emblem of India and is considered one of the finest pieces of Indian sculpture in existence.",
        tips: "Budget a half-day for the stupa, museum, and Mulagandha Kuti Vihara (a modern temple with frescoes by a Japanese artist). Auto-rickshaw from Varanasi takes 20 minutes.",
        duration: "Half day",
        bestTime: "Morning",
      },
      {
        id: 5,
        title: "Old City Walk",
        subtitle: "Getting lost in the lanes of eternity",
        image: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?w=1200",
        where: "Old City (Kashi), Varanasi",
        description: "The lanes of Varanasi's old city (kashi) are among the most extraordinary urban environments on earth. Barely wide enough for two people to pass, they wind between temples and havelis, through flower markets at 4 AM, past silk weavers working wooden handlooms, and emerge suddenly at the river. Twelve thousand temples are said to exist within this one-square-kilometre grid.",
        tips: "Hire a local guide from an accredited agency for your first walk — the lanes have no logic without local knowledge. Wear closed-toe shoes. The walk is best done in the morning.",
        duration: "2–3 hours",
        bestTime: "Early morning",
      },
      {
        id: 6,
        title: "Banarasi Silk Workshop",
        subtitle: "Weaving gold thread on a wooden loom",
        image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200",
        where: "Handloom weavers' quarters, Varanasi",
        description: "Varanasi has produced fine silk brocade (Banarasi silk) for at least 2,000 years — the tradition of weaving gold and silver zari thread into silk fabric on handlooms. The finest Banarasi sarees take 6 months to complete and are the standard for Indian bridal wear. Weaver families in the Lallapura, Adampur, and Madanpura quarters still work the ancient pit-loom technique.",
        tips: "Ask your hotel to connect you with an authentic weaver family rather than a showroom. Many families welcome visitors and will demonstrate the loom process. Verify authenticity of silk with the burn test before buying.",
        duration: "1–2 hours",
        bestTime: "Morning",
      },
      {
        id: 7,
        title: "Sankat Mochan Temple at Dusk",
        subtitle: "Where Hanuman's blessing arrives with music",
        image: "https://images.unsplash.com/photo-1545063914-a1a6ec821c88?w=1200",
        where: "Sankat Mochan Mandir, Varanasi",
        description: "Sankat Mochan is Varanasi's most beloved temple dedicated to Hanuman, founded by the poet-saint Tulsidas in the 16th century. Unlike the heavily commercialised Kashi Vishwanath Temple, this one retains an intimate, living devotion. Evenings bring spontaneous music — devotees sit in the courtyard playing harmonium and tabla for hours without any arranged programme.",
        tips: "Non-Hindus are welcome. Remove shoes at the entrance. Evening puja (around 7 PM) draws the most devotees and the most music. The adjacent Tulsi Manas Mandir has the entire Ramcharitmanas inscribed on its walls.",
        duration: "1 hour",
        bestTime: "Evening",
      },
      {
        id: 8,
        title: "Kashi Cuisine Trail",
        subtitle: "Tasting the food of 3,000 years",
        image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200",
        where: "Chowk area and ghats, Varanasi",
        description: "Varanasi's food culture is as layered as its spiritual identity. The morning begins with kachori-sabzi and jalebi at Kachori Gali — street vendors who have been frying the same recipe for generations. Banarasi thandai (milk infused with rose, cardamom, saffron, and nuts) is served in clay cups. The blue lassi at the Vishwanath Lane shop, made since 1925, is topped with malai, dry fruits, and saffron.",
        tips: "Do the food trail in the morning when everything is freshest and coolest. Follow the locals — stalls with queues are reliable. Avoid drinking the water; stick to packaged or boiled water.",
        duration: "2–3 hours",
        bestTime: "Morning",
      },
    ],
  },
  mahabaleshwar: {
    destinationTitle: "Mahabaleshwar",
    destinationLocation: "Maharashtra",
    heroImage: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/12/ee/48/fb.jpg",
    intro: "Mist rolls off the Western Ghats, strawberry farms glow red, and waterfalls plunge into green valleys. These eight experiences are Mahabaleshwar at its best.",
    experiences: [
      {
        id: 1,
        title: "Strawberry Picking at Mapro Garden",
        subtitle: "The freshest strawberries you have ever tasted",
        image: "https://thumbs.dreamstime.com/b/families-picking-fresh-strawberries-strawberry-farm-rows-red-ripe-very-appetising-ready-to-be-picked-photo-taken-156448665.jpg",
        where: "Mapro Garden, 3 km from Mahabaleshwar",
        description: "Mahabaleshwar produces 85% of India's strawberry crop, and Mapro Garden — a 15-acre processing facility and farm — is the best place to experience the harvest first-hand. Visitors can pick strawberries directly off the plant between December and March, and the garden makes fresh strawberry products on-site: ice cream, crushes, jams, and chocolate-dipped strawberries.",
        tips: "Picking season is December–March only. Arrive early before the best plants are picked clean. The factory tour shows the entire jam and crush production process.",
        duration: "1.5–2 hours",
        bestTime: "December–March, morning",
      },
      {
        id: 2,
        title: "Arthur's Seat Viewpoint",
        subtitle: "The Queen of Viewpoints over the Savitri Valley",
        image: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/12/ee/48/fb.jpg",
        where: "Arthur's Seat, 12 km from Mahabaleshwar",
        description: "Arthur's Seat sits at 1,470 metres at the edge of the plateau and offers a sheer 600-metre drop into the Savitri River valley below — a drop so dramatic that objects thrown from the edge are carried back up by the updraft. The Sahyadri mountains unfold in layers of receding blue across the horizon.",
        tips: "Best visibility is in winter (October–February). Avoid monsoon season (June–September) when the cliffside path can be dangerous. The walk from the road takes about 15 minutes.",
        duration: "1 hour",
        bestTime: "Morning, October–February",
      },
      {
        id: 3,
        title: "Venna Lake Boating",
        subtitle: "Quiet water in a forest of ferns and mist",
        image: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=1200",
        where: "Venna Lake, Mahabaleshwar",
        description: "Venna Lake is a man-made reservoir built in 1842 surrounded by dense semi-evergreen forest. The lake's calm surface reflects the surrounding trees and the mist that drifts through the Sahyadris on most mornings. Rowing boats, pedal boats, and motor boats are available for hire.",
        tips: "Avoid weekends when the lake gets crowded. The morning light on the water is exceptional before 9 AM. Small vendors sell fresh corn and strawberry ice cream around the lake perimeter.",
        duration: "1.5 hours",
        bestTime: "Morning",
      },
      {
        id: 4,
        title: "Pratapgad Fort",
        subtitle: "Shivaji's greatest military stronghold",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjhrD_fNF3IbBdf4Xrj0x2bLb4NPKQQKTz3g&s",
        where: "Pratapgad, 24 km from Mahabaleshwar",
        description: "Pratapgad Fort was built in 1656 under the direct supervision of Chhatrapati Shivaji Maharaj and is the site of the Battle of Pratapgad (1659) — one of Shivaji's most significant military victories. The fort rises 1,080 metres above sea level and commands views of three valleys.",
        tips: "Hire a car or cab from Mahabaleshwar — no public transport. The 500-step climb is moderate. Start before 10 AM to avoid afternoon mist reducing visibility.",
        duration: "3–4 hours including travel",
        bestTime: "Morning, October–March",
      },
      {
        id: 5,
        title: "Panchgani Table Land",
        subtitle: "Walk the second largest volcanic plateau in Asia",
        image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200",
        where: "Panchgani, 19 km from Mahabaleshwar",
        description: "Table Land is a vast, flat basalt plateau rising above Panchgani at 1,350 metres — the second largest volcanic plateau in Asia after the Deccan Plateau itself. The rock is entirely flat and stretches for over 1 km, dropping sheer on three sides into deep ravines.",
        tips: "Drive from Mahabaleshwar takes 25 minutes. The plateau is best visited in the afternoon when the mist sometimes lifts and the light is warm. Horse rides are negotiable — fix the price and route before mounting.",
        duration: "2 hours",
        bestTime: "Afternoon",
      },
      {
        id: 6,
        title: "Lingmala Waterfall",
        subtitle: "A 600-foot cascade through dense forest",
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/b0/12/1f/the-majestic-lingmala.jpg?w=1200&h=-1&s=1",
        where: "Lingmala, 6 km from Mahabaleshwar",
        description: "Lingmala Waterfall drops in two stages — the upper fall of about 500 feet and a lower fall of 100 feet — through a gorge of dense green jungle that includes the endemic Maharashtrian shrubbery and tree species of the Sahyadri.",
        tips: "Maharashtra Forest Department controls access — entry fee applies. The viewpoint platform provides the best view of the upper fall. Climbing toward the falls is restricted and genuinely dangerous.",
        duration: "1.5 hours",
        bestTime: "June–October for volume; November–March for comfort",
      },
      {
        id: 7,
        title: "Elephant's Head Point",
        subtitle: "The rock that fooled geology into art",
        image: "https://thumbs.dreamstime.com/b/elephant-point-mahabaleshwar-closeup-view-elephant-point-mahabaleshwar-closeup-view-asia-179642206.jpg",
        where: "Elephant's Head Point, 6 km from Mahabaleshwar",
        description: "A basalt rock formation at the edge of the plateau that, through millennia of weathering and erosion, has taken on the unmistakable profile of an elephant's head, complete with a trunk pointing downward toward the valley.",
        tips: "Combine with Babington Point (nearby viewpoint) and Wilson Point for a full morning viewpoint tour. The forest path between viewpoints is beautiful — walk rather than drive where possible.",
        duration: "45 minutes",
        bestTime: "Morning",
      },
      {
        id: 8,
        title: "Old Mahabaleshwar Temple Complex",
        subtitle: "Five rivers, five temples, 500 years of pilgrimage",
        image: "https://t4.ftcdn.net/jpg/19/34/43/39/360_F_1934433944_9VAUZxxKy5zBE0eIt0FOo3p37PBY5ItR.jpg",
        where: "Old Mahabaleshwar, 6 km from New Mahabaleshwar",
        description: "Old Mahabaleshwar is the original settlement — a cluster of stone temples built in the 16th century under the Maratha ruler Chandrarao More, predating the British hill station by 250 years. The Panchganga Temple contains a single natural spring from which five rivers are said to originate: the Krishna, Koyna, Venna, Savitri, and Gayatri.",
        tips: "Dress modestly for the temples. The temple complex is most active during morning puja (7–9 AM). The area is quiet compared to the tourist town — a genuinely atmospheric visit.",
        duration: "1.5 hours",
        bestTime: "Morning",
      },
    ],
  },
  udaipur: {
    destinationTitle: "Udaipur",
    destinationLocation: "Rajasthan",
    heroImage: "https://images.unsplash.com/photo-1621360841013-c7683c659ec6?w=1600",
    intro: "Venice of the East, City of Lakes, the city of romantic palaces and sunset boat rides. These eight experiences capture Udaipur's timeless allure.",
    experiences: [
      {
        id: 1,
        title: "Lake Pichola Boat Ride",
        subtitle: "Glide past the floating Lake Palace",
        image: "https://thumbs.dreamstime.com/b/lake-pichola-udaipur-view-city-rajasthan-india-203501215.jpg",
        where: "Lake Pichola, Udaipur",
        description: "A sunset boat ride on Lake Pichola is Udaipur's signature experience. You'll pass the Jag Mandir palace and the world-famous Lake Palace (now a luxury hotel), with the City Palace and Aravalli hills reflecting in the water.",
        tips: "Book the sunset departure (timings vary by season). Private boats cost more but offer better photo angles. Avoid midday when heat is intense.",
        duration: "1–2 hours",
        bestTime: "Sunset",
      },
      {
        id: 2,
        title: "City Palace Complex",
        subtitle: "The largest palace complex in Rajasthan",
        image: "https://t4.ftcdn.net/jpg/01/86/03/91/360_F_186039131_DtzFlukfaDy0Fdsgq6HzJwGGJ1II5Ls9.jpg",
        where: "City Palace, Udaipur",
        description: "Overlooking Lake Pichola, the City Palace is a series of palaces built by successive rulers from 1559. The complex includes courtyards, galleries, and the Crystal Gallery displaying items never used.",
        tips: "Allocate at least 3 hours. The audio guide is excellent. Don't miss the Zenana Mahal (Queen's quarters) and the miniature painting museum.",
        duration: "3–4 hours",
        bestTime: "Morning",
      },
      {
        id: 3,
        title: "Jagdish Temple",
        subtitle: "Indo-Aryan architecture at its finest",
        image: "https://t4.ftcdn.net/jpg/04/97/96/23/360_F_497962304_7KXUejdjUfhx4Y5zni0ooLuer7GlVlom.jpg",
        where: "City Palace Road, Udaipur",
        description: "Built in 1651 by Maharana Jagat Singh I, this temple is dedicated to Lord Vishnu. It features a 1.5-metre-high image of Vishnu as Jagannath, and the carved pillars are covered with detailed sculptures.",
        tips: "Visit during morning aarti (7 AM) for a spiritual experience. Modest dress required. The temple is free and centrally located near the City Palace.",
        duration: "30–45 minutes",
        bestTime: "Morning",
      },
      {
        id: 4,
        title: "Sajjangarh Fort (Monsoon Palace)",
        subtitle: "Sunset views over 1000 square kilometres",
        image: "https://t4.ftcdn.net/jpg/03/58/35/27/360_F_358352741_X0EavWfHOHKXuBMY5CZrPv9SyyseQX4n.jpg",
        where: "Sajjangarh, 5 km from Udaipur",
        description: "Built in 1884 by Maharana Sajjan Singh as an astronomical centre, the Monsoon Palace sits atop a hill offering panoramic views of Udaipur's lakes, palaces, and the surrounding countryside.",
        tips: "Arrive 1 hour before sunset. The drive up is steep — hire an auto or taxi. Carry water and a jacket (it gets windy).",
        duration: "1.5–2 hours",
        bestTime: "Late afternoon",
      },
      {
        id: 5,
        title: "Sahelion-ki-Bari",
        subtitle: "The Garden of the Maidens",
        image: "https://t4.ftcdn.net/jpg/02/96/24/15/360_F_296241588_SUyJcotha6hH0iZHMqP9tqrd1V36DrdW.jpg",
        where: "Sahelion-ki-Bari, Udaipur",
        description: "Built by Maharana Sangram Singh for his queen and her 48 attendants, this garden features fountains, marble elephants, kiosks, and a beautiful lotus pool. The fountains still work via the original water system.",
        tips: "Best visited in morning or late afternoon. The garden is small but very photogenic. Combine with a nearby street food stop.",
        duration: "1 hour",
        bestTime: "Morning",
      },
      {
        id: 6,
        title: "Bagore-ki-Haveli Dance Show",
        subtitle: "Folk music and puppetry under the stars",
        image: "https://thumbs.dreamstime.com/b/india-rajasthan-udaipur-traditional-indian-dance-lok-dharohar-haveli-dancers-carry-flaming-brass-pots-their-heads-india-359204446.jpg",
        where: "Gangori Bazaar, Udaipur",
        description: "Every evening at 7 PM, this 18th-century haveli hosts a cultural show featuring Rajasthani folk dances, puppet shows, and turban-tying demonstrations. The highlight is the dancer with 10 brass pots balanced on her head.",
        tips: "Book tickets in advance during peak season. Arrive by 6:30 PM for good seats. The show lasts about 1 hour.",
        duration: "1 hour",
        bestTime: "Evening",
      },
      {
        id: 7,
        title: "Vintage Car Museum",
        subtitle: "The Maharanas' classic car collection",
        image: "https://images.unsplash.com/photo-1621360841013-c7683c659ec6?w=1200",
        where: "Garden Hotel, Udaipur",
        description: "Housed in the former garage of the Maharana of Mewar, this museum displays 22 vintage cars including a 1938 Cadillac, a 1939 Buick, and the Rolls Royce used in the film 'Octopussy'.",
        tips: "Museum is small but fascinating for car enthusiasts. Combine with a visit to the nearby Fateh Sagar Lake. Photography allowed.",
        duration: "1 hour",
        bestTime: "Morning",
      },
      {
        id: 8,
        title: "Shilpgram Craft Village",
        subtitle: "Rural arts and crafts from across India",
        image: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?w=1200",
        where: "Shilpgram, 3 km from Udaipur",
        description: "A crafts village built to showcase traditional Indian art forms, with huts designed in the architecture of different states. Artisans work on-site selling pottery, textiles, woodwork, and jewellery.",
        tips: "Visit during the Shilpgram Festival (December) for a vibrant fair. Bargaining is expected. Allow 2 hours to explore the entire complex.",
        duration: "2 hours",
        bestTime: "Morning",
      },
    ],
  },
  rishikesh: {
    destinationTitle: "Rishikesh",
    destinationLocation: "Uttarakhand",
    heroImage: "https://images.unsplash.com/photo-1530731141654-5993c3016c77?w=1600",
    intro: "Yoga, adrenaline, and spirituality meet on the banks of the Ganges. These eight experiences take you from white-water rapids to silent meditation caves.",
    experiences: [
      {
        id: 1,
        title: "White Water Rafting",
        subtitle: "Conquer the Ganges rapids",
        image: "https://images.unsplash.com/photo-1629248457649-b082812aea6c?w=1200",
        where: "Shivpuri to Rishikesh stretch",
        description: "The Ganges near Rishikesh offers Grade III and IV rapids with names like 'Roller Coaster', 'Golf Course', and 'The Wall'. The 16 km stretch from Shivpuri to Rishikesh takes about 2–3 hours and includes several exciting rapids.",
        tips: "Book with a certified operator. Wear quick-dry clothes and secure footwear. Best season is October–June (monsoon closure July–September).",
        duration: "2–3 hours",
        bestTime: "October–June",
      },
      {
        id: 2,
        title: "Ganga Aarti at Parmarth Niketan",
        subtitle: "Evening prayer on the holy river",
        image: "https://thumbs.dreamstime.com/b/ganga-aarti-ceremony-parmarth-niketan-ashram-sunset-rishikesh-world-capital-yoga-has-numerous-centres-also-india-175231808.jpg",
        where: "Parmarth Niketan Ashram, Rishikesh",
        description: "The evening Ganga Aarti at Parmarth Niketan is the largest and most elaborate in Rishikesh. The ceremony includes chanting, fire offerings, and floating diyas on the river, with the Himalayas as a backdrop.",
        tips: "Arrive by 5:30 PM to get a seat on the steps. The aarti starts around sunset. Remove shoes before entering the ghat area.",
        duration: "1.5 hours",
        bestTime: "Daily at sunset",
      },
      {
        id: 3,
        title: "Beatles Ashram (Chaurasi Kutia)",
        subtitle: "Where the Beatles found transcendental meditation",
        image: "https://cdn.getyourguide.com/img/tour/b2f8aa0e14b9af96c32aede7d18c595a38b935bf6e90f07bc4106e6209bc7d5e.png/68.jpg",
        where: "Swarg Ashram, Rishikesh",
        description: "This abandoned ashram became famous when the Beatles stayed here in 1968 to practice Transcendental Meditation. Today it's a graffiti-covered ruin with meditation cells, a lecture hall, and the Beatles' signature preserved on a wall.",
        tips: "Entry fee required. Bring water — there are no shops inside. Best visited in morning or late afternoon for cooler temperatures and good light for photos.",
        duration: "1.5–2 hours",
        bestTime: "Morning",
      },
      {
        id: 4,
        title: "Bungee Jumping at Jumpin Heights",
        subtitle: "83 metres of pure adrenaline",
        image: "https://t4.ftcdn.net/jpg/01/79/96/69/360_F_179966921_KmXAtx9s0dbuEp0t9RpK7wjgP0YFmh0w.jpg",
        where: "Mohan Chatti, Rishikesh",
        description: "India's highest bungee jump at 83 metres into the Ganges gorge. Operated by Jumpin Heights, it meets international safety standards. The free fall lasts about 5 seconds before the cord rebounds.",
        tips: "Minimum age 12, minimum weight 40 kg. Book online in advance. The package includes a t-shirt and a video. Allow half a day including travel from Rishikesh.",
        duration: "2–3 hours",
        bestTime: "October–June",
      },
      {
        id: 5,
        title: "Yoga Retreat",
        subtitle: "Find your inner peace",
        image: "https://static.vecteezy.com/system/resources/thumbnails/075/605/360/small/diverse-friends-doing-pilates-class-golden-hour-outdoor-field-photo.jpg",
        where: "Multiple ashrams and centres in Rishikesh",
        description: "Known as the 'Yoga Capital of the World', Rishikesh offers everything from drop-in classes to multi-week teacher trainings. Try a 2-day retreat at Parmarth Niketan or a morning Hatha session at the International Yoga Centre.",
        tips: "Many ashrams offer free or donation-based classes. Check class times in advance. Wear comfortable clothing and bring your own mat if possible.",
        duration: "1 hour to several days",
        bestTime: "September–May (monsoon can be humid)",
      },
      {
        id: 6,
        title: "Laxman Jhula & Ram Jhula",
        subtitle: "Iconic suspension bridges over the Ganges",
        image: "https://t3.ftcdn.net/jpg/03/74/93/04/360_F_374930485_QhvZlb4F5saU51kebDT2jRvZsuijbxms.jpg",
        where: "Laxman Jhula, Rishikesh",
        description: "These two iron suspension bridges are landmarks of Rishikesh. Laxman Jhula (450 ft long) is said to be where Lord Laxman crossed the river on jute ropes. Ram Jhula is slightly newer. Walk across for temple views and market stalls.",
        tips: "Laxman Jhula is now pedestrian-only. Visit at sunset for the best light. The bridge can be crowded — go early morning for a calmer experience.",
        duration: "1 hour",
        bestTime: "Sunset or sunrise",
      },
      {
        id: 7,
        title: "Neer Garh Waterfall Trek",
        subtitle: "A hidden cascade a short hike away",
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/35/48/57/wanderer-gourav-bnqkjirhf1s.jpg?w=1200&h=-1&s=1",
        where: "Neer Garh, 5 km from Rishikesh",
        description: "A 1-km easy trek through forest leads to a two-tier waterfall with natural pools perfect for swimming. The falls are most spectacular post-monsoon (September–November). Local villagers have built bamboo bridges and platforms.",
        tips: "Small entry fee. Carry swimwear and a towel. Best visited in morning to avoid crowds. Combine with a trip to the nearby Kunjapuri Temple for sunrise views.",
        duration: "2–3 hours",
        bestTime: "September–March",
      },
      {
        id: 8,
        title: "Cafe Hopping in Tapovan",
        subtitle: "International flavours with mountain views",
        image: "https://www.shutterstock.com/image-photo/group-positive-pretty-asian-female-600nw-2405844319.jpg",
        where: "Tapovan area, Rishikesh",
        description: "Tapovan has become Rishikesh's cafe hub, offering everything from Israeli shakshuka to Italian wood-fired pizza. Popular spots include Little Buddha Cafe (Ganga view from a cliff), 60's Cafe (retro decor), and The Beatles Cafe (Beatles memorabilia).",
        tips: "Many cafes have live music in evenings. Most close by 10 PM due to the spiritual atmosphere of the town. Try the banana pancakes and chai.",
        duration: "1–2 hours",
        bestTime: "Breakfast or sunset",
      },
    ],
  },
  darjeeling: {
    destinationTitle: "Darjeeling",
    destinationLocation: "West Bengal",
    heroImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1600",
    intro: "A colonial-era hill station with Himalayan views, steam trains, and tea gardens that roll down the mountain slopes. These eight experiences are Darjeeling at its best.",
    experiences: [
      {
        id: 1,
        title: "Toy Train Ride",
        subtitle: "UNESCO Himalayan Railway journey",
        image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200",
        where: "Darjeeling Railway Station",
        description: "The Darjeeling Himalayan Railway (DHR), built between 1879 and 1881, is a UNESCO World Heritage site. The 2-hour joy ride from Darjeeling to Ghum (India's highest railway station) passes through Batasia Loop with views of Kanchenjunga.",
        tips: "Book tickets at least a day in advance at the station. The steam locomotive rides are only on specific days — check before booking.",
        duration: "2 hours",
        bestTime: "Morning",
      },
      {
        id: 2,
        title: "Tiger Hill Sunrise",
        subtitle: "First light on Kanchenjunga and Everest",
        image: "https://images.unsplash.com/photo-1590077538740-05e44d7b1560?w=1200",
        where: "Tiger Hill, 11 km from Darjeeling",
        description: "At 2,590 metres, Tiger Hill offers the most famous Himalayan sunrise in India. On clear mornings, you can see the peaks of Kanchenjunga (world's third highest) and even Mount Everest (8,848m) glowing gold as the sun rises.",
        tips: "Depart from Darjeeling at 4 AM by pre-arranged taxi. Dress very warmly — it's below freezing before sunrise. The viewpoint can be crowded; arrive early for a good spot.",
        duration: "3–4 hours including travel",
        bestTime: "October–December, February–April",
      },
      {
        id: 3,
        title: "Happy Valley Tea Estate",
        subtitle: "Walk through working tea gardens",
        image: "https://www.kiomoi.com/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fkmadmin%2Fimage%2Fupload%2Fc_scale%2Cw_500%2Ff_auto%2Fv1618487578%2Fkiomoi%2FDarjeeling_Happy_Valley_Tea_Estate_1618487577155.jpg&w=3840&q=75",
        where: "Happy Valley, 2 km from Darjeeling",
        description: "Established in 1854, this is one of Darjeeling's oldest tea estates. A guided tour takes you through the tea gardens, the factory where the leaves are withered, rolled, fermented, and dried, and ends with a tasting of first-flush Darjeeling tea.",
        tips: "The best time for tea plucking is March–May (first flush) and June–August (second flush). Wear comfortable walking shoes. The on-site shop sells fresh tea.",
        duration: "1.5–2 hours",
        bestTime: "Morning",
      },
      {
        id: 4,
        title: "Batasia Loop",
        subtitle: "The spiral railway with war memorial views",
        image: "https://darjeelingadventuretourism.com/images/batasia-loop-780.jpg",
        where: "Batasia Loop, 5 km from Darjeeling",
        description: "A spiral railway loop built to manage steep gradients, Batasia Loop offers panoramic views of Darjeeling town and Kanchenjunga. The Gorkha War Memorial here honours soldiers who died in various wars. The steam train often stops here for photos.",
        tips: "Visit after the Toy Train ride — the train stops here. Early morning offers the clearest mountain views. The garden is well-maintained with flowerbeds.",
        duration: "30–45 minutes",
        bestTime: "Morning",
      },
      {
        id: 5,
        title: "Japanese Peace Pagoda",
        subtitle: "Buddhist stupa with Himalayan backdrop",
        image: "https://helpthetourists.in/destination/img/darjeeling/japanese-peace-pagoda/5.webp",
        where: "Japati, Darjeeling",
        description: "One of 80 Peace Pagodas built worldwide by Japanese Buddhist monk Nichidatsu Fujii. This white stupa features four large golden Buddha statues. The surrounding gardens offer some of the best views of Kanchenjunga.",
        tips: "Visit late afternoon for golden light on the stupa and mountains. Remove shoes before entering the pagoda area. The walk up from the road is steep.",
        duration: "1 hour",
        bestTime: "Afternoon",
      },
      {
        id: 6,
        title: "Padmaja Naidu Himalayan Zoological Park",
        subtitle: "Home to red pandas and snow leopards",
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/32/d6/c6/b5/caption.jpg?w=900&h=500&s=1",
        where: "Darjeeling town, near Himalayan Mountaineering Institute",
        description: "India's only specialised high-altitude zoo, this is one of the best places to see red pandas, snow leopards, Tibetan wolves, and Himalayan black bears in near-natural enclosures. The zoo also runs breeding programmes for these endangered species.",
        tips: "Combine with the adjacent Himalayan Mountaineering Institute. Best time to see animals active is morning (9–11 AM). Winter months have the clearest visibility.",
        duration: "2–3 hours",
        bestTime: "Morning",
      },
      {
        id: 7,
        title: "Ghoom Monastery",
        subtitle: "The 15-foot Maitreya Buddha",
        image: "https://media.istockphoto.com/id/2223969191/photo/beautiful-view-of-interior-of-ghum-monastery-image-taken-with-permission-peaceful-calm-and.jpg?s=612x612&w=0&k=20&c=O58kI1GMpxKf_xSq_3lPC1EpIBfoF4geCPLXWOAXyKs=",
        where: "Ghoom, 8 km from Darjeeling",
        description: "Yiga Choeling Monastery (Ghoom Monastery) was built in 1850 and is one of the oldest in the region. The 4.5-metre-high statue of Maitreya Buddha (the Future Buddha) is the main attraction. The monastery houses many rare Tibetan scrolls and thankas.",
        tips: "Visit before noon for the best light on the statue. A small donation is appreciated. Photography is allowed but no flash inside the prayer hall.",
        duration: "1 hour",
        bestTime: "Morning",
      },
      {
        id: 8,
        title: "Mall Road Walk & Local Food",
        subtitle: "Colonial-era promenade with momos and thukpa",
        image: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?w=1200",
        where: "The Mall, Darjeeling",
        description: "The Mall is Darjeeling's main promenade — a 2-km stretch lined with colonial-era buildings, shops, and eateries. Sample local Tibetan food like momos (dumplings), thukpa (noodle soup), and alu dum. Keventers at the end of the Mall is a institution.",
        tips: "The Mall is vehicle-free, making it perfect for a sunset stroll. Keventers is cash-only and closes by 6 PM. Try the hot chocolate and pork sausages.",
        duration: "1.5–2 hours",
        bestTime: "Late afternoon",
      },
    ],
  },
  andaman: {
    destinationTitle: "Andaman",
    destinationLocation: "Bay of Bengal",
    heroImage: "https://images.unsplash.com/photo-1589197331516-4d836306915c?w=1600",
    intro: "Turquoise waters, white sandy beaches, and coral reefs teeming with life. These eight experiences will make you fall in love with India's island paradise.",
    experiences: [
      {
        id: 1,
        title: "Scuba Diving at Havelock Island",
        subtitle: "Explore the coral gardens of the Andaman Sea",
        image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200",
        where: "Elephant Beach, Havelock (Swaraj Dweep)",
        description: "Havelock Island offers some of the best scuba diving in India. Dive sites like 'The Wall', 'Seduction Point', and 'Johnny's Gorge' feature coral formations, reef sharks, moray eels, and enormous groupers.",
        tips: "Book with a certified dive shop (e.g., Dive India, Barefoot Scuba). Best visibility: October–May. No prior experience needed for beginner dives (DSD).",
        duration: "Half day (2 dives)",
        bestTime: "October–May",
      },
      {
        id: 2,
        title: "Radhanagar Beach",
        subtitle: "Asia's best beach, as rated by Time Magazine",
        image: "https://thumbs.dreamstime.com/b/wide-angle-view-famous-radhanagar-beach-swaraj-dweep-havelock-island-andaman-nicobar-islands-scene-features-449453153.jpg",
        where: "Radhanagar, Havelock Island",
        description: "Voted Asia's best beach in 2004 by Time Magazine, Radhanagar (Beach No. 7) is a 2-km stretch of pure white sand fringed by turquoise water. The sunset here is legendary — the sky and water turn shades of orange, pink, and purple.",
        tips: "Visit for sunset (5–6 PM) or early morning for a quieter experience. The beach has facilities including changing rooms and a small cafe. Swimming is safe but watch for currents.",
        duration: "2 hours",
        bestTime: "Sunset",
      },
      {
        id: 3,
        title: "Cellular Jail Light & Sound Show",
        subtitle: "The story of India's freedom struggle",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHNAm9uA-QRFYBdvTsqu0xPdWaBV4HFokNpg&s",
        where: "Cellular Jail, Port Blair",
        description: "This colonial-era prison housed political prisoners during the Indian freedom struggle. The evening light and sound show narrates the jail's history in Hindi and English, with the prison's architecture providing a moving backdrop.",
        tips: "Book tickets in advance. English show timings vary — check at the entrance. Arrive 15 minutes early. The show lasts about 1 hour.",
        duration: "1 hour show + 1 hour museum",
        bestTime: "Evening",
      },
      {
        id: 4,
        title: "Sea Walking at North Bay",
        subtitle: "Walk on the ocean floor without getting wet",
        image: "https://images.unsplash.com/photo-1582967788606-a171c1080cb0?w=1200",
        where: "North Bay Island, Port Blair",
        description: "Helmet diving (sea walking) allows you to walk on the seabed at a depth of 3–4 metres with a helmet that feeds you air from the surface. You'll be surrounded by coral fish — no swimming skills required.",
        tips: "Book through a government-approved operator. Underwater photography is available for purchase. Best season: December–April. The activity is safe for non-swimmers.",
        duration: "30 minutes underwater + boat transfers",
        bestTime: "Morning",
      },
      {
        id: 5,
        title: "Baratang Mangrove & Limestone Caves",
        subtitle: "Creek boat ride through ancient forests",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200",
        where: "Baratang Island, 100 km from Port Blair",
        description: "A day trip to Baratang includes a boat ride through dense mangrove creeks, a trek through tropical forest, and the limestone caves — stalactite and stalagmite formations created over thousands of years.",
        tips: "Start very early (5 AM) from Port Blair. The journey includes a forest permit check. Carry snacks and water — limited options on Baratang. Wear comfortable shoes for the cave trek.",
        duration: "Full day",
        bestTime: "December–April",
      },
      {
        id: 6,
        title: "Ross Island Ruins",
        subtitle: "The forgotten British capital of Andaman",
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/78/a4/51/ross-castle.jpg?w=1200&h=-1&s=1",
        where: "Ross Island, 2 km from Port Blair",
        description: "Once the administrative headquarters of the British in the Andamans, Ross Island was abandoned after an earthquake in 1941. Today, banyan trees have taken over the ruins of churches, bakeries, and the chief commissioner's house — a hauntingly beautiful scene.",
        tips: "Take the 15-minute ferry from Port Blair. Visit early morning to avoid heat and crowds. The light is best for photography. Wear mosquito repellent.",
        duration: "2–3 hours",
        bestTime: "Morning",
      },
      {
        id: 7,
        title: "Chidiya Tapu Sunset",
        subtitle: "Bird island and the best sunset in South Andaman",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRppH6FAh54fXRIj0ePRuIdgIkhEpoDHY_9A&s",
        where: "Chidiya Tapu, 25 km from Port Blair",
        description: "Chidiya Tapu (Bird Island) is a dense mangrove forest and a paradise for birdwatchers (over 40 species). But the main attraction is the sunset — the sun drops directly into the Bay of Bengal with no land interruption.",
        tips: "Arrive 1 hour before sunset. The sunset point has a viewing platform. Combine with the nearby Biological Park. Return to Port Blair before dark as roads are unlit.",
        duration: "1.5–2 hours",
        bestTime: "Late afternoon",
      },
      {
        id: 8,
        title: "Snorkelling at Neil Island",
        subtitle: "Shallow reefs perfect for beginners",
        image: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=1200",
        where: "Neil Island (Shaheed Dweep)",
        description: "Neil Island has pristine coral reefs accessible just 10–20 metres from the shore. Bharatpur Beach and Laxmanpur Beach offer excellent snorkelling with parrotfish, butterflyfish, and sometimes sea turtles. The calm, shallow water makes it ideal for families.",
        tips: "Bring your own snorkel gear for hygiene. Avoid high tide (reefs are deeper). Combine with the famous 'Natural Bridge' rock formation on Laxmanpur Beach.",
        duration: "Half day",
        bestTime: "December–April",
      },
    ],
  },
  jaisalmer: {
    destinationTitle: "Jaisalmer",
    destinationLocation: "Rajasthan",
    heroImage: "https://images.unsplash.com/photo-1631461761744-2000e7d27314?w=1600",
    intro: "The Golden City rises from the Thar Desert like a mirage. Sand dunes, Jain temples, and havelis carved from golden sandstone — these eight experiences are pure magic.",
    experiences: [
      {
        id: 1,
        title: "Sam Sand Dunes Camel Safari",
        subtitle: "Sunset over the Thar Desert",
        image: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=1200",
        where: "Sam Sand Dunes, 42 km from Jaisalmer",
        description: "A camel safari through the Sam Sand Dunes at sunset is the quintessential Jaisalmer experience. Ride a camel to the top of a dune, watch the sun paint the sand gold and orange, and then enjoy a traditional Rajasthani dinner and folk music around a campfire.",
        tips: "Book an overnight camp for the full experience. The best dunes for photography are at sunset and sunrise. Carry a scarf for sand and sun.",
        duration: "Half day to overnight",
        bestTime: "November–February, late afternoon",
      },
      {
        id: 2,
        title: "Jaisalmer Fort",
        subtitle: "The living fort of the Golden City",
        image: "https://images.unsplash.com/photo-1558791792-7c8051ba8bc2?w=1200",
        where: "Jaisalmer town centre",
        description: "Unlike most Indian forts, Jaisalmer Fort (Sonar Quila) is a living fort — a quarter of the city's population still lives inside its walls. Built in 1156, the golden-sandstone fort contains palaces, temples, havelis, shops, and homes, all within its winding lanes.",
        tips: "Enter via the Ganesh Pol. Hire a local guide to navigate the maze of lanes. Best visited early morning before the heat and crowds.",
        duration: "2–3 hours",
        bestTime: "Morning",
      },
      {
        id: 3,
        title: "Patwon-ki-Haveli",
        subtitle: "The most elaborate haveli in Jaisalmer",
        image: "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?w=1200",
        where: "Patwon-ki-Haveli, Jaisalmer",
        description: "This is a cluster of five havelis built by a wealthy merchant in the early 19th century. The intricate stone carvings, balconies, and arches are the finest examples of Jaisalmer's distinctive architecture.",
        tips: "The museum section requires a ticket. Photography is allowed. Combine with nearby Salim Singh-ki-Haveli and Nathmal-ki-Haveli for a haveli walking tour.",
        duration: "1 hour",
        bestTime: "Morning",
      },
      {
        id: 4,
        title: "Jain Temples Inside the Fort",
        subtitle: "Exquisite marble and stone carvings",
        image: "https://images.unsplash.com/photo-1524492712937-b28074a5d7da?w=1200",
        where: "Jaisalmer Fort, Jaisalmer",
        description: "Dedicated to Jain tirthankaras, these 15th-century temples are known for their elaborate stone carvings, domes, and spires. The main temple is dedicated to Rishabhdev, and the intricate detailing on the ceilings and pillars is breathtaking.",
        tips: "Non-Jains are allowed. Remove shoes before entering. Photography is not allowed inside the main shrine. The temples are active — morning aarti is a good time to visit.",
        duration: "1 hour",
        bestTime: "Morning",
      },
      {
        id: 5,
        title: "Desert National Park & Bada Bagh",
        subtitle: "Ancient cenotaphs and desert wildlife",
        image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=1200",
        where: "Bada Bagh, 6 km from Jaisalmer",
        description: "Bada Bagh is a garden complex with chhatris (cenotaphs) of Maharajas of Jaisalmer, built from golden sandstone and rising from the desert. It's a stunning place at sunset. Nearby Desert National Park is home to the Great Indian Bustard, desert foxes, and chinkara.",
        tips: "Visit Bada Bagh at sunset for the best light. Desert National Park visit requires early morning departure. Combine with a visit to the Vyas Chhatri.",
        duration: "1.5 hours",
        bestTime: "Sunset",
      },
      {
        id: 6,
        title: "Gadisar Lake",
        subtitle: "The man-made oasis of Jaisalmer",
        image: "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=1200",
        where: "Gadisar Lake, 1 km from Jaisalmer",
        description: "Built in 1367 by Maharaja Gadsi Singh, this artificial lake was once the main water source for Jaisalmer. Today it's a peaceful spot surrounded by temples, chhatris, and birdlife. Rent a paddleboat or just walk the stone steps around the water.",
        tips: "Best visited at sunrise or sunset. Watch for migratory birds November–February. The adjacent shrines are photogenic. Carry water — it can get hot.",
        duration: "1 hour",
        bestTime: "Sunset or sunrise",
      },
      {
        id: 7,
        title: "Kuldhara Village",
        subtitle: "The cursed ghost village",
        image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1200",
        where: "Kuldhara, 18 km from Jaisalmer",
        description: "This abandoned village was once home to Paliwal Brahmins. Legend says they cursed the village and vanished overnight in the 19th century to avoid persecution. Today, the ruins of 200 houses remain eerily intact, with a palpable sense of emptiness.",
        tips: "Best visited in late afternoon for atmospheric light. There's an entry fee and an audio guide available. Many visitors report feeling 'presences' — it's part of the experience.",
        duration: "1–1.5 hours",
        bestTime: "Late afternoon",
      },
      {
        id: 8,
        title: "Folklore Museum & Dinner at a Heritage Haveli",
        subtitle: "A cultural evening in the Golden City",
        image: "https://images.unsplash.com/photo-1561501900-3701fa6a0864?w=1200",
        where: "Various heritage hotels in Jaisalmer",
        description: "The Folklore Museum (part of the Moomal Hotel) showcases Rajasthani art, costumes, and puppets. Follow it with dinner at a restored haveli-turned-hotel like Bhairo Vilas or Suryagarh, where you can eat traditional Rajasthani thali under the stars while watching folk dancers and musicians.",
        tips: "Book the dinner in advance. Many heritage hotels offer cultural evenings even if you're not staying there. The Folklore Museum is small but worth 30 minutes.",
        duration: "2–3 hours",
        bestTime: "Evening",
      },
    ],
  },
};